_1 = [
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
    "P                                                                                    P",
    "P                                                                                    P",
    "P                           E                                        E               P",
    "P                     PPPPPPPPPPP                              PPPPPPPPPPP           P",
    "P                                                                                    P",
    "P                                                                                    P",
    "P                                                                                    P",
    "P     PPPPPPPP                                 PPPPPPPP                              P",
    "P                                                                                    P",
    "P                           PPPPPPP                                  PPPPPPP         P",
    "P                  PPPPPP                                   PPPPPP                   P",
    "P                                                                                    P",
    "P          PPPPPPP                                  PPPPPPP                          P",
    "P                                                                                    P",
    "P                      PPPPPP                                   PPPPPP               P",
    "P                                                                                    P",
    "P    PPPPPPPPPPP                              PPPPPPPPPPP                            P",
    "P                                                                                    P",
    "P                     PPPPPPP                                  PPPPPPP               P",
    "P                                                                                    P",
    "P                  PPPPPPPPPPP                              PPPPPPPPPPP              P",
    "P                                                                                    P",
    "P                                                                                    P",
    "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
]
