WIN_WIDTH = 800
WIN_HEIGHT = int(WIN_WIDTH / 1.25)
HALF_WIDTH = int(WIN_WIDTH / 2)
HALF_HEIGHT = int(WIN_HEIGHT / 2)
BLK_SIZE = 32

DISPLAY = (WIN_WIDTH, WIN_HEIGHT)
DEPTH = 32
FLAGS = 0
CAMERA_SLACK = 30

BACKGROUND_COLOR = "#000000"
PLATFORM_COLOR = "#DDDDDD"
EXIT_BLOCK_COLOR = "#C0C0C0"
CHARACTER_COLOR = "#0000FF"
NPC_COLOR = "#FF0000"

